{
 "title": "Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "django_active_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM usage %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "django_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "django_cpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory usage MB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "django_memory_usage_mb", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "django_http_requests_before_middlewares_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}