# """
# Django settings for core project.

# Generated by 'django-admin startproject' using Django 5.2.14.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from datetime import timedelta
# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-4foc3q6ki3r=cux4ug9wa)0phx&3wy_i3sq^89y)o*fr#-xvwr'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django_prometheus',
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'shop',
#     'rest_framework',
#     'celery',

# ]

# # set the celery broker url
# CELERY_BROKER_URL = 'redis://localhost:6379/0'

# # set the celery result backend
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# # set the celery timezone
# CELERY_TIMEZONE = 'UTC'


# MIDDLEWARE = [
#     'django_prometheus.middleware.PrometheusBeforeMiddleware',
#     'shop.system_metrics_middleware.SystemMetricsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     #'django.middleware.csrf.CsrfViewMiddleware',
#     # 'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'django_prometheus.middleware.PrometheusAfterMiddleware',
# ]

# ROOT_URLCONF = 'core.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'core.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'shop_db',
#         'USER': 'root',
#         'PASSWORD': 'judyjudy',
#         'HOST': 'localhost',
#         'PORT': '3306',
#          'CONN_MAX_AGE': 60,  # reuse connections for 60 seconds
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# AUTH_USER_MODEL = 'shop.User'

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
# }
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#         # تعطيل SessionAuthentication يمنع ديجانغو من البحث عن CSRF token في Postman
#         # 'rest_framework.authentication.SessionAuthentication',
#         # 'rest_framework.authentication.SessionAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     )
# }
# from django.db.backends.base.base import BaseDatabaseWrapper
# from django.db.backends.mysql.base import DatabaseFeatures

# # 1. إجبار دجانغو على تجاوز فحص تحديث قاعدة البيانات عند الإقلاع
# BaseDatabaseWrapper.check_database_version_supported = lambda self: None

# # 2. إجبار دجانغو على عدم استخدام ميزة RETURNING غير المتوافقة مع نسختك الحالية
# DatabaseFeatures.can_return_rows_from_bulk_insert = property(lambda self: False)
# DatabaseFeatures.can_return_columns_from_insert = property(lambda self: False)


from django.db.backends.mysql.base import DatabaseFeatures
from django.db.backends.base.base import BaseDatabaseWrapper
from datetime import timedelta
from pathlib import Path
import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-4foc3q6ki3r=cux4ug9wa)0phx&3wy_i3sq^89y)o*fr#-xvwr',
)
DEBUG = env_bool('DEBUG', True)
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]

INSTALLED_APPS = [
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'rest_framework',
    'celery',
]

DB_HOST = os.environ.get('DB_HOST', 'localhost')
DB_PORT = os.environ.get('DB_PORT', '3306')
DB_NAME = os.environ.get('DB_NAME', 'shop_db')
DB_USER = os.environ.get('DB_USER', 'root')
DB_PASSWORD = os.environ.get('DB_PASSWORD', 'judyjudy')
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TIMEZONE = 'UTC'

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'shop.system_metrics_middleware.SystemMetricsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    'shop.middleware.CorrelationIdMiddleware'
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST,
        'PORT': DB_PORT,
        'CONN_MAX_AGE': 0,
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "db": "1",           # DB 1 to separate cache from Celery (DB 0)
        },
        "KEY_PREFIX": "shop",
        "TIMEOUT": 300,          # default 5 min, overridden per-view in cache_utils.py
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'shop.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}


BaseDatabaseWrapper.check_database_version_supported = lambda self: None
DatabaseFeatures.can_return_rows_from_bulk_insert = property(
    lambda self: False)
DatabaseFeatures.can_return_columns_from_insert = property(lambda self: False)


BASE_DIR = Path(__file__).resolve().parent.parent


BASE_DIR = Path(__file__).resolve().parent.parent
LOG_BASE_DIR = os.path.join(BASE_DIR, 'logs')

# system services
SERVICES = ['auth', 'orders', 'shop', 'inventory']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'correlation_filter': {
            '()': 'shop.middleware.CorrelationIdFilter', 
        }
    },
    'formatters': {
        'simple': {
            'format': '[{asctime}] [{correlation_id}] {levelname}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['correlation_filter'],
            'formatter': 'simple',
        },
    },
    'loggers': {}
}

for service in SERVICES:
    service_log_dir = os.path.join(LOG_BASE_DIR, service)
    os.makedirs(service_log_dir, exist_ok=True) 
# info handlers
    LOGGING['handlers'][f'{service}_info'] = {
        'level': 'INFO',
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(service_log_dir, 'info.log'),
        'maxBytes': 1024 * 1024 * 5, # 5MB
        'backupCount': 3,
        'filters': ['correlation_filter'],
        'formatter': 'simple',
    }

  # errors handlers
    LOGGING['handlers'][f'{service}_error'] = {
        'level': 'WARNING', # Catches WARNING, ERROR, and CRITICAL
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': os.path.join(service_log_dir, 'errors.log'),
        'maxBytes': 1024 * 1024 * 5,
        'backupCount': 5,
        'filters': ['correlation_filter'],
        'formatter': 'simple',
    }

    # Register the unique Logger for this service
    LOGGING['loggers'][f'service.{service}'] = {
        'handlers': ['console', f'{service}_info', f'{service}_error'],
        'level': 'DEBUG',
        'propagate': False,
    }