# Generated by Django 5.2.14 on 2026-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateTimeField(auto_now_add=True, verbose_name='Audit Date & Time')),
                ('method_used', models.CharField(max_length=50, verbose_name='Processing Method')),
                ('total_orders_processed', models.IntegerField(verbose_name='Total Orders Processed')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Sales Amount')),
                ('execution_time', models.FloatField(verbose_name='Execution Time (Seconds)')),
                ('ram_consumption', models.FloatField(verbose_name='RAM Consumption (MB)')),
                ('status', models.CharField(default='Success', max_length=20, verbose_name='Audit Status')),
            ],
            options={
                'verbose_name': 'Daily Audit Log',
                'verbose_name_plural': 'Daily Audit Logs',
                'ordering': ['-audit_date'],
            },
        ),
    ]
